export type IFormValues = {

    依頼事項: string;
    開通希望日: string;
    ご契約社名: string;
    ドメイン: string;
    ご契約サービス: string;
    ご契約アカウント数: number;
    ユーザー認証方式: string;
    'SAML_担当者名': string;
    'SAML_担当者メールアドレス': string;
    'SAML_IdPサービス名': string;
    'SAML_IdPメタデータ': FileList;
    'LDAP/Active Directory': string;
    'LDAP_サーバーFQDN/IP': string;
    'LDAP_ポート番号': number;
    'LDAP_BaseDN': string;
    'LDAP_文字コード': string;
    'LDAP_ログインアカウント': string;
    'LDAP_ログインパスワード': string;
    'LDAP_フィルタ': string;
    'O365・G_suite切替': string;
    '切替前のMXレコード': string;
    '切替後のMXレコード': string;
    'MXレコード': string[];
    '中継許可サーバーIPアドレス': string;
    '中継先サーバーIPアドレス': string;
    '中継先サーバーFQDN': string;
    '中継先サーバー': string[];
    '認証_サーバー': string;
    '認証_ポート番号': number;
    '認証サーバー': string[];
    'POP認証時にメールアドレス全体で認証する': string;
    'DKIM認証を利用する': string;
    'MGΣプラン': string[];
    'アクセスURL_第1希望':string;
    'アクセスURL_第2希望': string;
    'アクセスURL_第3希望': string;
    'MailGates_IPアクセス制御': string;
    'MXレコード切替予定日': string;
    '管理者メールアドレス1': string;
    '管理者メールアドレス2': string;
    '管理者メールアドレス3': string;
    '管理者メールアドレス4': string;
    '管理者メールアドレス5': string;
    'パートナー_会社名': string;
    'パートナー_部署': string;
    'パートナー_担当者名': string;
    'パートナー_メールアドレス': string;
    'パートナー_電話番号': string;
    'サポート窓口_会社名': string;
    'サポート窓口_担当者名': string;
    'サポート窓口_メールアドレス': string;
    'サポート窓口_電話番号': string;
    '開通通知用_会社名': string;
    '開通通知用_担当者名': string;
    '開通通知用_TO宛先': string;
    }